log4cplus.rootLogger=INFO, Console
log4cplus.appender.Console=log4cplus::ConsoleAppender
log4cplus.appender.Console.layout=log4cplus::PatternLayout
log4cplus.appender.Console.layout.ConversionPattern=%d{%H:%M:%S} %-5p %c - %m%n